"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold #f2f4f8)[](#be95ff)\
$os\
$username\
[](bg:#d79921 fg:#be95ff)\
$directory\
[](fg:#d79921 bg:#33b1ff)\
$git_branch\
$git_status\
[](fg:#33b1ff bg:#78a9ff)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#78a9ff bg:#393939)\
$docker_context\
$conda\
$pixi\
[](fg:#393939 bg:#262626)\
$time\
[ ](fg:#262626)
[│](bold #f2f4f8)
[╰─](bold #f2f4f8) """

[palettes.oxocarbon_dark]
color_fg0 = "#f2f4f8"  # base05
color_bg1 = "#262626"   # base01
color_bg3 = "#393939"   # base02
color_blue = "#78a9ff"  # base09
color_aqua = "#3ddbd9"  # base08
color_green = "#42be65" # base0D
color_orange = "#ee5396" # base0A (now pink-red)
color_purple = "#be95ff" # base0E (accent)
color_red = "#ee5396"   # base0A
color_yellow = "#be95ff" # base0E (purple as accent)

[os]
disabled = false
style = "bg:#be95ff fg:#161616"  # Purple accent with dark text

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:#be95ff fg:#161616"  # Purple accent
style_root = "bg:#ee5396 fg:#161616"   # Red for root
format = '[ $user ]($style)'

[directory]
style = "fg:#161616 bg:#d79921"  # Yellow background
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# ... (keep all directory substitutions) ...

[git_branch]
symbol = ""
style = "bg:#33b1ff"  # Blue
format = '[[ $symbol $branch ](fg:#161616 bg:#33b1ff)]($style)'

[git_status]
style = "bg:#33b1ff"
format = '[[($all_status$ahead_behind )](fg:#161616 bg:#33b1ff)]($style)'

# All language modules (c, cpp, rust, etc.)
# Unified style using blue (#78a9ff)
[nodejs]
symbol = ""
style = "bg:#78a9ff"
format = '[[ $symbol( $version) ](fg:#161616 bg:#78a9ff)]($style)'

[c]
symbol = " "
style = "bg:#78a9ff"
format = '[[ $symbol( $version) ](fg:#161616 bg:#78a9ff)]($style)'

# ... (apply same style to all other language modules) ...

[docker_context]
symbol = ""
style = "bg:#393939"
format = '[[ $symbol( $context) ](fg:#3ddbd9 bg:#393939)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#262626"
format = '[[  $time ](fg:#f2f4f8 bg:#262626)]($style)'

[character]
success_symbol = '[](bold fg:#42be65)'
error_symbol = '[](bold fg:#ee5396)'
vimcmd_symbol = '[](bold fg:#42be65)'
vimcmd_replace_one_symbol = '[](bold fg:#be95ff)'  # Purple
vimcmd_replace_symbol = '[](bold fg:#be95ff)'     # Purple
vimcmd_visual_symbol = '[](bold fg:#d79921)'      # Yellow
