background_opacity 0.7
font_family JetBrains Mono NF
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0

window_padding_width 5
hide_window_decorations no
confirm_os_window_close 0

# Colors based on Catppuccin Mocha
foreground #cdd6f4
background #1e1e2e
selection_foreground #45475a
selection_background #cdd6f4

# Black
color0 #181825
color8 #313244

# Red
color1 #f38ba8
color9 #f38ba8

# Green
color2 #a6e3a1
color10 #a6e3a1

# Yellow
color3 #f9e2af
color11 #f9e2af

# Blue
color4 #89b4fa
color12 #89b4fa

# Magenta
color5 #cba6f7
color13 #cba6f7

# Cyan
color6 #94e2d5
color14 #94e2d5

# White
color7 #cdd6f4
color15 #f5e0dc

# Cursor
cursor #b4befe
cursor_text_color #1e1e2e

# Tab bar
active_tab_foreground #b4befe
active_tab_background #181825
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

# Window border
active_border_color #b4befe
inactive_border_color #313244

# URL
url_color #b4befe
